INSERT INTO zap_report (
    site_name,
    site_host,
    site_port,
    site_ssl,
    pluginid,
    alertRef,
    alert,
    name,
    riskcode,
    confidence,
    riskdesc,
    confidencedesc,
    description,
    instance_uri,
    instance_method,
    instance_param,
    instance_attack,
    instance_evidence,
    instance_otherinfo,
    count,
    solution,
    otherinfo,
    reference,
    cweid,
    wascid,
    sourceid
) VALUES (
    'https://public-firing-range.appspot.com',
    'public-firing-range.appspot.com',
    443,
    1,
    10028,
    '10028',
    'Open Redirect',
    'Open Redirect',
    3,
    2,
    'High (Medium)',
    'Medium',
    '<p>Open redirects are one of the OWASP 2010 Top Ten vulnerabilities. This check looks at user-supplied input in query string parameters and POST data to identify where open redirects might be possible. Open redirects occur when an application allows user-supplied input (e.g. https://nottrusted.com) to control an offsite redirect. This is generally a pretty accurate way to find where 301 or 302 redirects could be exploited by spammers or phishing attacks.</p><p></p><p>For example an attacker could supply a user with the following link: https://example.com/example.php?url=https://malicious.example.com.</p>',
    'https://public-firing-range.appspot.com/urldom/redirect?url=http://example.com',
    'GET',
    'url',
    '',
    '',
    'The 301 or 302 response to a request for the following URL appeared to contain user input in the location header:\n\nhttps://public-firing-range.appspot.com/urldom/redirect?url=http://example.com\n\nThe user input found was:\n\nurl=http://example.com\n\nThe context was:\n\nhttp://example.com',
    1,
    '<p>To avoid the open redirect vulnerability, parameters of the application script/program must be validated before sending 302 HTTP code (redirect) to the client browser. Implement safe redirect functionality that only redirects to relative URI\'s, or a list of trusted domains</p>',
    '<p>The 301 or 302 response to a request for the following URL appeared to contain user input in the location header:</p><p></p><p>https://public-firing-range.appspot.com/urldom/redirect?url=http://example.com</p><p></p><p>The user input found was:</p><p></p><p>url=http://example.com</p><p></p><p>The context was:</p><p></p><p>http://example.com</p>',
    '<p>https://cheatsheetseries.owasp.org/cheatsheets/Unvalidated_Redirects_and_Forwards_Cheat_Sheet.html</p><p>https://cwe.mitre.org/data/definitions/601.html</p>',
    601,
    38,
    703
);